### ISSUE TITLE
Inline HTML image data is not folded when "base64fold_all_uris": true

### ISSUE THREAD

**Issue by keith-hall** [DaQuirm/base64-fold#11]
When `"base64fold_all_uris": true` is set in the Preferences (which is the default), inline "img src" base64 data isn't folded automatically on save or load.

Example:

    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />

**Comment by DaQuirm** [comment]
Fixed by #13
