### ISSUE TITLE
Multiline base64 data is not folded correctly

### ISSUE THREAD

**Issue by keith-hall** [DaQuirm/base64-fold#12]
> Data URIs encoded in Base64 may contain whitespace for human readability.

(From https://en.wikipedia.org/wiki/Data_URI_scheme#Syntax)

Example:

    <!DOCTYPE html>
    <html>
    <head>
        <title></title>
    </head>
    <body>
        <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA
        AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />

        <style type="text/css">
        span {
            padding-left: 20px;
            background:white  url('data:image/png;base64,iVBORw0KGgoAA\
                AANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUAAAD///+l2Z/dAAAAM0l\
                EQVR4nGP4/5/h/1+G/58ZDrAz3D/McH8yw83NDDeNGe4Ug9C9zwz3gVLMDA/A6\
                P9/AFGGFyjOXZtQAAAAAElFTkSuQmCC') no-repeat scroll left top;
        }
        /* Backslashes at end of line - to continue character string
             at new line. */
        </style>
        <span>Test</span>
    </body>
    </html>

Currently the `img` only gets the first line (`iVBORw0KGgoAAAANSUhEUgAAAAUA`) folded ([with `base64fold_all_uris` set to false](https://github.com/DaQuirm/base64-fold/issues/11)), leaving the other lines unfolded. The `uri('` in the CSS doesn't get folded at all.

CC @Kristinita re: https://github.com/SublimeTextIssues/Core/issues/513#issuecomment-281290123

**Comment by DaQuirm** [comment]
Hello @keith-hall 
I'm terribly sorry, but at the moment I don't have enough free time to investigate this issue (and the other one you opened).
It should be a simple regex fix, if you don't mind contributing 😉

**Comment by keith-hall** [comment]
It turned out not to be massively simple (though it was certainly fun!), but I took the liberty of addressing one of your other outstanding issues while I was working on it, I hope you don't mind too much :)

**Comment by DaQuirm** [comment]
Thank you for your contribution! I'm glad it was fun to hack on this and _you even added more tests!_ 😻

**Comment by Kristinita** [comment]
@keith-hall , thanks for changes! But base64 data URI don't split automatically for human readability and Sublime Text syntax highlighting. We need to create feature request to [**Image2Base64**](https://github.com/tm-minty/sublime-text-2-image2base64) package or here?

Thanks.

**Comment by keith-hall** [comment]
You'll want to create a feature request at the Image2Base64 package for that, or manually format the base64

**Comment by Kristinita** [comment]
@keith-hall , I don't understand: is it a question?

Thanks.

**Comment by keith-hall** [comment]
@Kristinita Nope, it wasn't a question - I'm saying that this package, base64-fold, is for code folding only. In my opinion, it shouldn't be changed to alter the contents of the files in any way. As you are using the Image2Base64 plugin to generate the base64, it would make sense if you created a feature request there, so that it would wrap the base64 that it generates to a certain number of characters per line. Alternatively, or for existing base64 code inside your files, you could manually insert line breaks where you want them.

**Comment by Kristinita** [comment]
@keith-hall , [**my feature request**](https://github.com/tm-minty/sublime-text-2-image2base64/issues/12).

Thanks.
