### ISSUE TITLE
base64 not folding in markdown file

### ISSUE THREAD

**Issue by inwardmovement** [DaQuirm/base64-fold#14]
base64 is not folding in markdown (.md) file

**Comment by DaQuirm** [comment]
@inwardmovement Does it help if you add .md to the list of file extensions [here](https://github.com/DaQuirm/base64-fold/blob/master/Base64%20Fold.sublime-settings#L14)?

**Comment by inwardmovement** [comment]
For now I'm not concerned any more because I ended up moving the base64 code outside my .md file (it's better for user experience when viewing the md files, in ST or on GitHub).

I have `base64fold_any_file` and `base64fold_all_uris` to true, but your suggestion could benefit other people, thank you.

**Comment by DaQuirm** [comment]
I see, shall we close this then?

**Comment by inwardmovement** [comment]
As you wish!

**Comment by DaQuirm** [comment]
Closing, If you reproduce this or a similar issue feel free to reopen
