### ISSUE TITLE
Feature request: fold data:image/svg+xml

### ISSUE THREAD

**Issue by certainlyakey** [DaQuirm/base64-fold#7]
See [here](https://css-tricks.com/probably-dont-base64-svg/). This is a useful technique that allows to include SVG code in CSS file. Usually looks like

````
list-style-image: url('data:image/svg+xml;utf8,<svg width="11px" height="11px" xmlns="http://www.w3.org/2000/svg"><path d="M6.56713392,6.3167819 ... Z" fill="red" stroke="black" stroke-width="1"></path></svg>'); 
````

**Comment by DaQuirm** [comment]
Hmmm, this could be a built-into feature or a User preference (e.g. array
of regex patterns to fold in data-uri's). What do you think?

**Comment by certainlyakey** [comment]
User preference is more flexible, but built-in feature is certainly more user friendly) Don't know what to prefer. Is it safe to fold anything in CSS that begins with `data:`?

**Comment by DaQuirm** [comment]
Sorry for having disappeared, I was preoccupied with my relocation. I started working on this feature, can't give the ETA yet, but expect it soon! :smiley_cat:

**Comment by certainlyakey** [comment]
That's cool, good luck with this!

**Comment by DaQuirm** [comment]
Finally, a more universal folding mode is here (see 8161dc96)! All data URIs will be folded now by default, this behavior can be turned off in [preferences](https://github.com/DaQuirm/base64-fold/blob/master/Base64%20Fold.sublime-settings). Package Control's channel should be updated within an hour; see if the new version works for you.  :sparkles:

**Comment by DaQuirm** [comment]
Closing the issue for now, feel free to reopen
